trigger:
  - main
  - develop
  - patch/*

pr:
  - main
  - develop
  - patch/*

parameters:
  - name: buildExternals
    displayName: 'The specific native artifacts to use for this build.'
    type: number
    default: 5800178
  - name: VM_IMAGE_WINDOWS
    type: string
    default: 'Azure-Pipelines-windows-2022'
  - name: VM_IMAGE_WINDOWS_NATIVE
    type: string
    default: 'Azure-Pipelines-windows-2019'
  - name: VM_IMAGE_MAC
    type: string
    default: 'Azure-Pipelines-macOS-10.15'
  - name: VM_IMAGE_LINUX
    type: string
    default: 'Azure-Pipelines-ubuntu-18.04'

variables:
  - template: azure-pipelines-variables.yml

resources:
  repositories:
    - repository: xamarin-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main

stages:
  - template: azure-templates-stages.yml
    parameters:
      isBuildPipeline: true
      buildExternals: ${{ parameters.buildExternals }}
      VM_IMAGE_WINDOWS: ${{ parameters.VM_IMAGE_WINDOWS }}
      VM_IMAGE_WINDOWS_NATIVE: ${{ parameters.VM_IMAGE_WINDOWS_NATIVE }}
      VM_IMAGE_MAC: ${{ parameters.VM_IMAGE_MAC }}
      VM_IMAGE_LINUX: ${{ parameters.VM_IMAGE_LINUX }}
